export const DEFAULT_THEMES = [
    {
        id: "warm-bakery",
        name: "Warm Bakery",
        description: "Warm browns and golden tones",
        colors: {
            primary: "#8B4513",
            accent: "#D2691E",
            cream: "#FFF8E7",
            dark: "#5D4037",
            light: "#FFFFFF",
            text: "#5D4037",
            beige: "#F5F5DC",
            sand: "#E6DCC3",
        },
    },
    {
        id: "modern-minimal",
        name: "Modern Minimal",
        description: "Clean black and white",
        colors: {
            primary: "#1a1a1a",
            accent: "#007bff",
            cream: "#f8f9fa",
            dark: "#1a1a1a",
            light: "#ffffff",
            text: "#1a1a1a",
            beige: "#e9ecef",
            sand: "#dee2e6",
        },
    },
    {
        id: "fresh-green",
        name: "Fresh & Green",
        description: "Natural green tones",
        colors: {
            primary: "#2E8B57",
            accent: "#3CB371",
            cream: "#F0FFF0",
            dark: "#1C4428",
            light: "#ffffff",
            text: "#1C4428",
            beige: "#E8F5E9",
            sand: "#C8E6C9",
        },
    },
    {
        id: "ocean-blue",
        name: "Ocean Blue",
        description: "Cool blue vibes",
        colors: {
            primary: "#1E90FF",
            accent: "#00CED1",
            cream: "#F0F8FF",
            dark: "#191970",
            light: "#ffffff",
            text: "#191970",
            beige: "#E3F2FD",
            sand: "#BBDEFB",
        },
    },
    {
        id: "sunset-warm",
        name: "Sunset Warm",
        description: "Warm sunset colors",
        colors: {
            primary: "#FF6B6B",
            accent: "#FFD93D",
            cream: "#FFF5EE",
            dark: "#8B0000",
            light: "#ffffff",
            text: "#8B0000",
            beige: "#FFEBEE",
            sand: "#FFCDD2",
        },
    },
    // New Themes
    {
        id: "midnight-luxury",
        name: "Midnight Luxury",
        description: "Elegant gold and black",
        colors: {
            primary: "#FFD700",
            accent: "#C0C0C0",
            cream: "#121212", // Dark background replacement for cream
            dark: "#000000",
            light: "#FFD700", // Gold text on dark
            text: "#F5F5F5", // Light text
            beige: "#1E1E1E", // Darker beige replacement
            sand: "#2C2C2C", // Darker sand replacement
        },
    },
    {
        id: "lavender-mist",
        name: "Lavender Mist",
        description: "Soft purple and calming tones",
        colors: {
            primary: "#9370DB",
            accent: "#E6E6FA",
            cream: "#F8F8FF",
            dark: "#4B0082",
            light: "#ffffff",
            text: "#4B0082",
            beige: "#F3E5F5",
            sand: "#E1BEE7",
        },
    },
    {
        id: "tropical-vibe",
        name: "Tropical Vibe",
        description: "Vibrant coral and turquoise",
        colors: {
            primary: "#FF7F50",
            accent: "#40E0D0",
            cream: "#FDFFF5",
            dark: "#FF4500",
            light: "#ffffff",
            text: "#2F4F4F",
            beige: "#FFF5EE",
            sand: "#FFE4C4",
        },
    },
    {
        id: "forest-rain",
        name: "Forest Rain",
        description: "Deep greens and earthy tones",
        colors: {
            primary: "#228B22",
            accent: "#8FBC8F",
            cream: "#F0FFF4",
            dark: "#006400",
            light: "#ffffff",
            text: "#1B4D3E",
            beige: "#E0F2F1",
            sand: "#B9F6CA",
        },
    },
    {
        id: "berry-smoothie",
        name: "Berry Smoothie",
        description: "Playful pinks and raspberries",
        colors: {
            primary: "#C71585",
            accent: "#FF69B4",
            cream: "#FFF0F5",
            dark: "#8B008B",
            light: "#ffffff",
            text: "#800080",
            beige: "#F8BBD0",
            sand: "#F48FB1",
        },
    },
    // Restaurant-Inspired Themes
    {
        id: "italian-trattoria",
        name: "Italian Trattoria",
        description: "Warm orange and rustic brown",
        colors: {
            primary: "#FF8C00",
            accent: "#D2691E",
            cream: "#FFF3E0",
            dark: "#4E2A04",
            light: "#ffffff",
            text: "#4E2A04",
            beige: "#FFE0B2",
            sand: "#FFCC80",
        },
    },
    {
        id: "sushi-zen",
        name: "Sushi Zen",
        description: "Dark red and black Japanese aesthetic",
        colors: {
            primary: "#8B0000",
            accent: "#C41E3A",
            cream: "#1A1A1A",
            dark: "#0D0D0D",
            light: "#E8D5B7",
            text: "#F5F0E8",
            beige: "#2A2A2A",
            sand: "#3A3A3A",
        },
    },
    {
        id: "french-bistro",
        name: "French Bistro",
        description: "Navy blue and gold elegance",
        colors: {
            primary: "#1B1F3B",
            accent: "#C9A96E",
            cream: "#FAF8F5",
            dark: "#0E1129",
            light: "#ffffff",
            text: "#1B1F3B",
            beige: "#F0EDE6",
            sand: "#E3DDD4",
        },
    },
    {
        id: "mexican-fiesta",
        name: "Mexican Fiesta",
        description: "Vibrant lime and warm red",
        colors: {
            primary: "#E63946",
            accent: "#A8D820",
            cream: "#FFFDE7",
            dark: "#B71C1C",
            light: "#ffffff",
            text: "#3E2723",
            beige: "#FFF9C4",
            sand: "#FFF176",
        },
    },
    {
        id: "rustic-steakhouse",
        name: "Rustic Steakhouse",
        description: "Deep leather brown and charcoal",
        colors: {
            primary: "#4E342E",
            accent: "#8D6E63",
            cream: "#EFEBE9",
            dark: "#3E2723",
            light: "#ffffff",
            text: "#3E2723",
            beige: "#D7CCC8",
            sand: "#BCAAA4",
        },
    },
    {
        id: "coastal-seafood",
        name: "Coastal Seafood",
        description: "Sandy beige and ocean teal",
        colors: {
            primary: "#008B8B",
            accent: "#20B2AA",
            cream: "#F5FFFE",
            dark: "#004D4D",
            light: "#ffffff",
            text: "#004D4D",
            beige: "#E0F7FA",
            sand: "#B2DFDB",
        },
    },
    {
        id: "matcha-cafe",
        name: "Matcha Café",
        description: "Muted sage green and cream",
        colors: {
            primary: "#7B8F6A",
            accent: "#A8BF96",
            cream: "#FAFDF6",
            dark: "#4A5D3A",
            light: "#ffffff",
            text: "#3E4A31",
            beige: "#EDF2E6",
            sand: "#D5E1C8",
        },
    },
    {
        id: "wine-bar",
        name: "Wine Bar",
        description: "Rich burgundy and champagne",
        colors: {
            primary: "#722F37",
            accent: "#D4A574",
            cream: "#FDF8F4",
            dark: "#4A1C22",
            light: "#ffffff",
            text: "#4A1C22",
            beige: "#F5EDE6",
            sand: "#E8D9CC",
        },
    },
    {
        id: "nordic-minimal",
        name: "Nordic Minimal",
        description: "Pale gray and warm wood tones",
        colors: {
            primary: "#6B7280",
            accent: "#C4A882",
            cream: "#FAFAFA",
            dark: "#374151",
            light: "#ffffff",
            text: "#374151",
            beige: "#F3F4F6",
            sand: "#E5E7EB",
        },
    },
    {
        id: "neon-street-food",
        name: "Neon Street Food",
        description: "Dark background with electric pink",
        colors: {
            primary: "#FF1493",
            accent: "#00FFFF",
            cream: "#0F0F0F",
            dark: "#000000",
            light: "#FF1493",
            text: "#F0F0F0",
            beige: "#1A1A2E",
            sand: "#16213E",
        },
    },
];
