export const DEFAULT_THEMES = [
    {
        id: "warm-bakery",
        name: "Warm Bakery",
        description: "Warm browns and golden tones",
        colors: {
            primary: "#8B4513",
            accent: "#D2691E",
            cream: "#FFF8E7",
            dark: "#5D4037",
            light: "#FFFFFF",
            text: "#5D4037",
            beige: "#F5F5DC",
            sand: "#E6DCC3",
        },
    },
    {
        id: "modern-minimal",
        name: "Modern Minimal",
        description: "Clean black and white",
        colors: {
            primary: "#1a1a1a",
            accent: "#007bff",
            cream: "#f8f9fa",
            dark: "#1a1a1a",
            light: "#ffffff",
            text: "#1a1a1a",
            beige: "#e9ecef",
            sand: "#dee2e6",
        },
    },
    {
        id: "fresh-green",
        name: "Fresh & Green",
        description: "Natural green tones",
        colors: {
            primary: "#2E8B57",
            accent: "#3CB371",
            cream: "#F0FFF0",
            dark: "#1C4428",
            light: "#ffffff",
            text: "#1C4428",
            beige: "#E8F5E9",
            sand: "#C8E6C9",
        },
    },
    {
        id: "ocean-blue",
        name: "Ocean Blue",
        description: "Cool blue vibes",
        colors: {
            primary: "#1E90FF",
            accent: "#00CED1",
            cream: "#F0F8FF",
            dark: "#191970",
            light: "#ffffff",
            text: "#191970",
            beige: "#E3F2FD",
            sand: "#BBDEFB",
        },
    },
    {
        id: "sunset-warm",
        name: "Sunset Warm",
        description: "Warm sunset colors",
        colors: {
            primary: "#FF6B6B",
            accent: "#FFD93D",
            cream: "#FFF5EE",
            dark: "#8B0000",
            light: "#ffffff",
            text: "#8B0000",
            beige: "#FFEBEE",
            sand: "#FFCDD2",
        },
    },
    // New Themes
    {
        id: "midnight-luxury",
        name: "Midnight Luxury",
        description: "Elegant gold and black",
        colors: {
            primary: "#FFD700",
            accent: "#C0C0C0",
            cream: "#121212", // Dark background replacement for cream
            dark: "#000000",
            light: "#FFD700", // Gold text on dark
            text: "#F5F5F5", // Light text
            beige: "#1E1E1E", // Darker beige replacement
            sand: "#2C2C2C", // Darker sand replacement
        },
    },
    {
        id: "lavender-mist",
        name: "Lavender Mist",
        description: "Soft purple and calming tones",
        colors: {
            primary: "#9370DB",
            accent: "#E6E6FA",
            cream: "#F8F8FF",
            dark: "#4B0082",
            light: "#ffffff",
            text: "#4B0082",
            beige: "#F3E5F5",
            sand: "#E1BEE7",
        },
    },
    {
        id: "tropical-vibe",
        name: "Tropical Vibe",
        description: "Vibrant coral and turquoise",
        colors: {
            primary: "#FF7F50",
            accent: "#40E0D0",
            cream: "#FDFFF5",
            dark: "#FF4500",
            light: "#ffffff",
            text: "#2F4F4F",
            beige: "#FFF5EE",
            sand: "#FFE4C4",
        },
    },
    {
        id: "forest-rain",
        name: "Forest Rain",
        description: "Deep greens and earthy tones",
        colors: {
            primary: "#228B22",
            accent: "#8FBC8F",
            cream: "#F0FFF4",
            dark: "#006400",
            light: "#ffffff",
            text: "#1B4D3E",
            beige: "#E0F2F1",
            sand: "#B9F6CA",
        },
    },
    {
        id: "berry-smoothie",
        name: "Berry Smoothie",
        description: "Playful pinks and raspberries",
        colors: {
            primary: "#C71585",
            accent: "#FF69B4",
            cream: "#FFF0F5",
            dark: "#8B008B",
            light: "#ffffff",
            text: "#800080",
            beige: "#F8BBD0",
            sand: "#F48FB1",
        },
    },
];
